### PR TITLE
adding blog post: Tales From a Mechanical Engineer

### PR DESCRIPTION
**Pull request by jgomez720**
@franknoirot the documentation submodule still confuses me a little, so I think the workflow for this is to merge to documentation -> update submodule in website repo -> start PR in website to generate vercel preview -> merge once approved?

### CODE REVIEW

**Comment by jgomez720** [comment]
related to https://github.com/KittyCAD/media-brand/issues/120

**Comment by jessfraz** [comment]
I like it!

**Comment by jgomez720** [comment]
@franknoirot I would say this is ready to go if you want to throw it in the queue of blog posts.

**Comment by franknoirot** [comment]
LGTM, you're right on the workflow but we don't need to update the submodule manually because we have a GitHub Action to do that and open a PR against the website with it updated.

**Pull request merged**
